import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import MUIDateProvioder from "@/Provider/MUIDateProvioder";
import { Toaster } from 'react-hot-toast';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MUIDateProvioder>

      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white antialiased`}
        >
        <Navbar />
        {children}
          <Toaster/>
      </body>
        </MUIDateProvioder>
    </html>
  );
}
